/** Simplified Chinese copy. */
export const zh = {
	"row.title": "接入 Qoder 积分与模型 (dsh-connect-qoder)",
	"row.desc": "使用本机已登录的 Qoder（国内版 / 国际版）模型；图像输入可以按模型逐个设置。",
	"row.expand": "展开",
	"row.collapse": "收起",
	"row.loading": "正在读取模型目录…",
	"row.signedOut": "没找到已登录的 Qoder 应用，所以没有模型。",
	"row.regionEmpty": "这个版本当前没有可展示的模型（未登录，或它的「模型」开关已关闭）。",
	"row.imageTitle": "图像输入",
	"row.imageHint": "「跟随目录」使用 Qoder 自己声明的视觉能力；「开启」/「关闭」是手动强制。开启后该模型可以接收图片。",
					"row.maxWindow": "按最大上下文显示",
				"row.maxWindowTitle": "开启时显示该模型支持的最大窗口；关闭时显示默认窗口。未列出窗口的模型不支持切换。",
				"row.maxWindowNote": "该模型未提供可切换的上下文窗口",
	"row.save": "保存",
	"row.saving": "保存中…",
	"row.saved": "已保存",
	"row.discard": "撤销更改",
	"row.unsaved": "有未保存的更改",
	"row.failed": "保存失败",
	"row.requestFailed": "读取模型目录失败",
	"row.imageAuto": "跟随目录",
	"row.imageOn": "开启",
	"row.imageOff": "关闭",
	"row.vision": "视觉",
	"row.textOnly": "纯文本",
	"row.region.qoder-cn": "国内版",
	"row.region.qoder": "国际版",
	"usage.title": "我的用量",
	"usage.refresh": "刷新",
	"usage.loading": "正在读取用量…",
	"usage.empty": "当前账户暂无可展示的用量。",
	"usage.unavailable": "这个区域暂时读不到用量。",
	"usage.none": "这个版本暂时没有用量数据（未登录或尚未上线）。",
	"usage.error": "读取用量失败",
	"usage.planCredits": "套餐内 Credits",
	"usage.resourcePackage": "个人资源包",
	"usage.dedicatedPackage": "专属资源包",
	"usage.renewsOn": "将于 {date} 续订",
	"usage.expiresOn": "将于 {date} 结束",
	"usage.remaining": "剩余",
	"usage.used": "已使用",
	"usage.exceeded": "额度用完",
	"usage.promotion": "限时特惠",
	"usage.viewDetails": "查看详情",
	"usage.credits": "Credits",
	"account.reload": "重新读取登录状态",
	"account.confirm": "在线校验登录",
	"account.confirming": "校验中…",
	"account.confirmed": "在线校验通过：登录有效",
	"account.confirmExpired": "在线校验发现登录已过期——在应用内重新登录后点「重新读取登录状态」",
	"account.confirmFailed": "在线校验失败：{detail}",
	"account.state.ok": "正常",
	"account.state.expired": "已过期",
	"account.state.needs-app": "读不到",
	"account.state.signed-out": "未登录",
	"account.envPat": "来自环境变量 PAT",
	"account.appFrom": "来自 {app}",
	"account.expiresAt": "有效期至 {date}",
	"account.unsigned": "本机没装这个版本的 Qoder 应用",
	"account.expiredHint": "请在应用里重新登录，然后点「重新读取登录状态」",
	"account.readFail": "本地登录信息读不到：{detail}",
	"account.openManage": "到 Qoder 管理页",
	"account.error": "读取账号状态失败",
	"account.offer": "模型",
	"account.offerTitle": "取消勾选就关闭这个版本：它的模型不会出现在 DSH 的模型下拉框里；登录、用量与模型设置都会保留，重新勾选即恢复。",
	"account.offerOff": "已关闭：该版本的模型不会出现在 DSH 的模型下拉框里",
	"account.offerError": "保存「模型」开关失败：{detail}",
	"account.regionTabs": "版本：点哪个就看哪个版本的账号、用量与模型",
	"row.showInPicker": "出现在模型下拉框",
	"row.showHint": "未勾选的模型不会出现在 DSH 的模型下拉框里。",
	"row.enableAll": "全部勾选",
	"row.disableAll": "全部取消勾选",
	"row.enabledCount": "已勾选 {count} / {total}",
	"row.rateFree": "免费",
	"row.rateLabel": "倍率",
	"row.refreshModels": "刷新计费",
	"row.refreshing": "正在刷新…",
	"row.refreshed": "已更新（{time}）",
	"row.offPeakOn": "错峰价",
	"row.offPeakOff": "标准价",
	"row.offPeakUntil": "{time} 后切换",
	"row.offPeakHint": "错峰时段 {window}（{zone}）享受折扣；倍率按当前时段显示，到点会自动变化。",
	// Search, error retry, and the Escape-to-collapse affordance.
	"row.search": "搜索模型",
	"row.searchPlaceholder": "输入模型名…",
	"row.searchEmpty": "没有匹配的模型。",
	"row.retry": "重试",
	"row.filterCount": "显示 {visible} / {total} · 已勾选 {ticked}",
	"row.clearFilter": "清除筛选"
};
/** English copy. */
export const en = {
	"row.title": "Connect Qoder credits and models (dsh-connect-qoder)",
	"row.desc": "Use the Qoder models already signed in on this machine (Qoder CN / Qoder); image input is decided per model.",
	"row.expand": "Expand",
	"row.collapse": "Collapse",
	"row.loading": "Reading the model catalog…",
	"row.signedOut": "No signed-in Qoder app was found, so there are no models.",
	"row.regionEmpty": "No models to show for this edition right now (not signed in, or its switch is off).",
	"row.imageTitle": "Image input",
	"row.imageHint": "\"Follow catalog\" uses Qoder's own vision flag; On/Off forces it. An enabled model accepts images.",
	"row.maxWindow": "Show each model's maximum context window",
	"row.maxWindowTitle": "On: show the widest window the model offers. Off: show the default window. Models with no listed window cannot be switched.",
	"row.maxWindowNote": "No switchable context window offered for this model",
	"row.save": "Save",
	"row.saving": "Saving…",
	"row.saved": "Saved",
	"row.discard": "Discard changes",
	"row.unsaved": "Unsaved changes",
	"row.failed": "Save failed",
	"row.requestFailed": "Could not read the model catalog",
	"row.imageAuto": "Follow catalog",
	"row.imageOn": "On",
	"row.imageOff": "Off",
	"row.vision": "Vision",
	"row.textOnly": "Text",
	"row.region.qoder-cn": "Qoder CN",
	"row.region.qoder": "Qoder",
	"usage.title": "My usage",
	"usage.refresh": "Refresh",
	"usage.loading": "Reading usage…",
	"usage.empty": "This account has no usage to show right now.",
	"usage.unavailable": "Usage is unavailable for this region right now.",
	"usage.none": "No usage data for this edition (not signed in, or offline yet).",
	"usage.error": "Could not read usage",
	"usage.planCredits": "Plan Credits",
	"usage.resourcePackage": "Personal resource package",
	"usage.dedicatedPackage": "Dedicated package",
	"usage.renewsOn": "Renews on {date}",
	"usage.expiresOn": "Ends on {date}",
	"usage.remaining": "remaining",
	"usage.used": "used",
	"usage.exceeded": "Quota exhausted",
	"usage.promotion": "Limited offer",
	"usage.viewDetails": "View details",
	"usage.credits": "Credits",
	"account.reload": "Re-read sign-in",
	"account.confirm": "Confirm online",
	"account.confirming": "Confirming…",
	"account.confirmed": "Confirmed: sign-in is valid",
	"account.confirmExpired": "Confirmed: sign-in expired — sign in again in the app, then re-read",
	"account.confirmFailed": "Could not confirm: {detail}",
	"account.state.ok": "OK",
	"account.state.expired": "Expired",
	"account.state.needs-app": "Unreadable",
	"account.state.signed-out": "Not signed in",
	"account.envPat": "from an environment PAT",
	"account.appFrom": "from {app}",
	"account.expiresAt": "Valid until {date}",
	"account.unsigned": "No Qoder app for this region is installed on this machine",
	"account.expiredHint": "Sign in again in the app, then click Re-read sign-in",
	"account.readFail": "Could not read the local credential: {detail}",
	"account.openManage": "Open the Qoder account page",
	"account.error": "Could not read the account states",
	"account.offer": "Models",
	"account.offerTitle": "Unchecking disables this edition: its models no longer appear in DSH's model picker; the sign-in, usage and model settings are kept, and re-checking restores them.",
	"account.offerOff": "Disabled: this edition's models are not offered to the model picker",
	"account.offerError": "Could not save the models switch: {detail}",
	"account.regionTabs": "Editions: pick which one's account, usage and models to view",
	"row.showInPicker": "Show in the model picker",
	"row.showHint": "An unchecked model is hidden from DSH's model picker.",
	"row.enableAll": "Check all",
	"row.disableAll": "Uncheck all",
	"row.enabledCount": "{count} of {total} checked",
	"row.rateFree": "free",
	"row.rateLabel": "Rate",
	"row.refreshModels": "Refresh rates",
	"row.refreshing": "Refreshing…",
	"row.refreshed": "Updated ({time})",
	"row.offPeakOn": "off-peak",
	"row.offPeakOff": "standard",
	"row.offPeakUntil": "switches in {time}",
	"row.offPeakHint": "The off-peak discount applies {window} ({zone}); the rate shown follows the current window and changes on its own at the boundary.",
	// Search, error retry, and the Escape-to-collapse affordance.
	"row.search": "Search models",
	"row.searchPlaceholder": "Type a model name…",
	"row.searchEmpty": "No matching models.",
	"row.retry": "Retry",
	"row.filterCount": "{visible} of {total} shown · {ticked} ticked",
	"row.clearFilter": "Clear filter"
};